language: minimal

addons:
  apt:
    update: true

before_install:
  - apt-get install -y python3 python3-pip python3-setuptools python3-wheel ninja-build
  - apt-get install -y libgtk-3-dev
  - pip3 install --user meson

script:
  - meson builddir && cd builddir
  - ninja
  - ninja test
  - ./demo
